=== hmcts/civil-sdt/producers-api/src/main/resources/xsd/DefenceRequest&Response/DefenceFeedbackRequest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://ws.sdt.moj.gov.uk" 
    targetNamespace="http://ws.sdt.moj.gov.uk"
	elementFormDefault="qualified">
    
	<xs:include schemaLocation="../RootXSDs/Base.xsd" />
	
    <xs:element name="defenceRequest" type="tns:defenceRequestType" />
    
	<xs:complexType name="defenceRequestType">
		<xs:sequence>
			<xs:element name="header" type="tns:headerType" />
			<xs:element name="criteria" type="tns:criteriaType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="headerType">
		<xs:sequence>
			<xs:element name="sdtCustomerId" type="tns:sdtCustomerId" />
			<xs:element name="targetSystemId" type="tns:targetSystemId" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="criteriaType">
		<xs:sequence>
			<xs:element name="mcolDefence" type="tns:mcolDefenceType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mcolDefenceType">
		<xs:sequence>
			<xs:element name="fromDate" type="xs:date" />
			<xs:element name="toDate" type="xs:date" />
		</xs:sequence>
	</xs:complexType>
	
	
</xs:schema>

=== hmcts/civil-sdt/producers-api/src/unit-test/resources/xml/validation/DefenceRequestResponse/DefenceFeedbackRequestIncorrectFormat.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:defenceRequest xmlns:tns="http://ws.sdt.moj.gov.uk/2013/sdt/DefenceFeedbackRequestSchema" xmlns:tns1="http://ws.sdt.moj.gov.uk/2013/sdt/BaseSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ws.sdt.moj.gov.uk/2013/sdt/DefenceFeedbackRequestSchema ../../../../../main/resources/xsd/DefenceRequestResponse/DefenceFeedbackRequest.xsd ">
  <tns:header>
    <tns:sdtCustomerId>123445678</tns:sdtCustomerId>
    <tns:targetApplicationId>mcol11</tns:targetApplicationId>
  </tns:header>
  <tns:criteria>
    <tns:mcolDefence>
      <tns:fromDate>200221-01-101</tns:fromDate>
      <tns:toDate>200122-01-011</tns:toDate>
    </tns:mcolDefence>
  </tns:criteria>
</tns:defenceRequest>
