=== hmcts/civil-sdt/producers-api/src/main/resources/xsd/RootXSDs/SetAside.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ws.sdt.moj.gov.uk/2013/mcol/SetAsideSchema"
	xmlns:tns="http://ws.sdt.moj.gov.uk/2013/mcol/SetAsideSchema"
	xmlns:base="http://ws.sdt.moj.gov.uk/2013/sdt/BaseSchema"
	elementFormDefault="qualified" version="1.0">

	<xs:import namespace="http://ws.sdt.moj.gov.uk/2013/sdt/BaseSchema"
		schemaLocation="Base.xsd" />


	<xs:simpleType name="setAsideStringType">
		<xs:restriction base="base:sdtNonBlankStringType">
			<xs:minLength value="1" />
			<xs:maxLength value="34" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="applicationTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="C" />
			<xs:enumeration value="D" />
			<xs:enumeration value="L" />
			<xs:enumeration value="O" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="applicantType">
		<xs:sequence>
			<xs:element name="applicantType" type="tns:applicationTypeType" minOccurs="1"/>
			<xs:element name="otherDetail" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="base:sdtNonBlankStringType">
						<xs:minLength value="1" />
						<xs:maxLength value="53" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="representing" type="tns:setAsideStringType"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="applicationHandlingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AH" />
			<xs:enumeration value="WH" />
			<xs:enumeration value="TH" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="hearingTimeEstimateType">
		<xs:sequence>
			<xs:element name="hours" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="999" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="minutes" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="59" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="agreedByAll" type="xs:boolean"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="serviceAddressType">
		<xs:sequence>
			<xs:element name="line1" type="base:nonBlankLineType" minOccurs="1" />
			<xs:element name="line2" type="base:nonBlankLineType" minOccurs="1" />
			<xs:element name="line3" type="base:lineType" minOccurs="0" />
			<xs:element name="line4" type="base:lineType" minOccurs="0" />
			<xs:element name="postcode" type="base:nonUKPostcodeType"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="servingTargetType">
		<xs:sequence>
			<xs:element name="serveApplicationTo" type="tns:setAsideStringType"
				minOccurs="0" />
			<xs:element name="serviceAddress" type="tns:serviceAddressType"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="supportingInformationTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="WS" />
			<xs:enumeration value="SC" />
			<xs:enumeration value="EV" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="evidenceType">
		<xs:restriction base="base:sdtNonBlankStringType">
			<xs:minLength value="1" />
			<xs:maxLength value="8000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="inSupportType">
		<xs:sequence>
			<xs:element name="supportingInformation" type="tns:supportingInformationTypeType"
				minOccurs="1" maxOccurs="3" />
			<xs:element name="evidence" type="tns:evidenceType"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="setAsideType">
		<xs:sequence>
			<xs:element name="claimNumber" type="base:claimNumberType"
				minOccurs="1" />

			<xs:element name="defendantId" type="base:defendantIdType"
				minOccurs="1" />
			<xs:element name="applicantType" type="tns:applicantType"
				minOccurs="1" />
			<xs:element name="orderAndDetails" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="base:sdtNonBlankStringType">
						<xs:minLength value="1" />
						<xs:maxLength value="3000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="applicationHandling" type="tns:applicationHandlingType" />

			<xs:element name="hearingTimeEstimates" type="tns:hearingTimeEstimateType"
				minOccurs="0" />
			<xs:element name="trialDetails" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="base:sdtNonBlankStringType">
						<xs:minLength value="0" />
						<xs:maxLength value="34" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="judgeLevel" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="base:sdtNonBlankStringType">
						<xs:minLength value="0" />
						<xs:maxLength value="34" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="servingTarget" type="tns:servingTargetType"
				minOccurs="0" />
			<xs:element name="inSupport" type="tns:inSupportType"
				minOccurs="1"/>
			<xs:element name="sotSignature" type="base:sotSignatureType"
				minOccurs="1">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="mcolSetAside" type="tns:setAsideType" />

</xs:schema>

=== hmcts/civil-sdt/producers-api/src/unit-test/resources/xml/validation/mcolType/SetAsideIncorrectFormat.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:mcolSetAside xmlns:tns="http://ws.sdt.moj.gov.uk/2013/mcol/SetAsideSchema" xmlns:tns1="http://ws.sdt.moj.gov.uk/2013/sdt/BaseSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ws.sdt.moj.gov.uk/2013/mcol/SetAsideSchema ../../../../../main/resources/xsd/RootXSDs/SetAside.xsd ">
  <tns:claimNumber>tns:claimNumber</tns:claimNumber>
  <tns:defendantId>1</tns:defendantId>
  <tns:applicantType>
    <tns:applicantType>z</tns:applicantType>
    <tns:otherDetail>tnsotherDetail</tns:otherDetail>
    <tns:representing>1234567890123456789012345678901234567890</tns:representing>
  </tns:applicantType>
  <tns:orderAndDetails>orderAndDetails</tns:orderAndDetails>
  <tns:applicationHandling>PH</tns:applicationHandling>
  <tns:hearingTimeEstimates>
    <tns:hours>2000</tns:hours>
    <tns:minutes>60</tns:minutes>
    <tns:agreedByAll>blah</tns:agreedByAll>
  </tns:hearingTimeEstimates>
  <tns:trialDetails>trialDetails</tns:trialDetails>
  <tns:judgeLevel>judgeLevel</tns:judgeLevel>
  <tns:servingTarget>
    <tns:serveApplicationTo>1</tns:serveApplicationTo>
    <tns:serviceAddress>
      <tns:line1>tns:line1</tns:line1>
      <tns:line2>tns:line2</tns:line2>
      <tns:line3>tns:line3</tns:line3>
      <tns:line4>tns:line4</tns:line4>
      <tns:postcode>tns:postcode</tns:postcode>
    </tns:serviceAddress>
  </tns:servingTarget>
  <tns:inSupport>
    <tns:supportingInformation>PS</tns:supportingInformation>
    <tns:supportingInformation>WS</tns:supportingInformation>
    <tns:supportingInformation>SC</tns:supportingInformation>
    <tns:supportingInformation>VS</tns:supportingInformation>
  </tns:inSupport>
  <tns:sotSignature>
    <tns1:flag>true</tns1:flag>
    <tns1:name>tns1:name</tns1:name>
  </tns:sotSignature>
</tns:mcolSetAside>
